language: python

python:
  - 3.6

install:
  - pip install --upgrade -r requirements.txt

script:
  - python3 -m unittest

notifications:
  email:
    recipients:
      - rugleb@gmail.com
    on_success: never
    on_failure: always
